Cargo.toml, src/lib.rs, src/serialization.rs, src/stringtable.rs
First commit initializes cargo in the repo. @michaelwoerister I added your info as you had it listed in the other repo. Is your email correct? 
Second commit copies over the string table sketch unchanged.
I have no idea how to setup highfive or bors so those aren't done. If you want to use plain-old travis, I think I know how to set that up (but have not done so in this PR).
=> Setup cargo & string_table sketch

examples/end_to_end.rs, src/event.rs, src/lib.rs, src/mmap_serialization_sink.rs, src/profiler.rs, src/profiling_data.rs, src/raw_event.rs, src/serialization.rs, src/stringtable.rs
This PR defines the basic data types and interfaces of the library.
`tests/end_to_end.rs` contains an example of how I roughly imagine the public API of the crate to look like.
~~This is not meant to be merged yet (it doesn't even compile).~~
cc @wesleywiser
=> Define basic interfaces and data structures

measureme/Cargo.toml
While working on https://github.com/rust-lang/rust/pull/59515, I noticed that some shared dependencies between rustc and measureme were getting updated when adding the measureme dependency. This commit changes our dependency versions to match those of rustc.
=> Change dependencies to match existing rustc deps

measureme/src/file_serialization_sink.rs, measureme/src/mmap_serialization_sink.rs, measureme/src/profiler.rs, measureme/src/serialization.rs, measureme/src/testing_common.rs
=> Implement better error handling

CHANGELOG.md, summarize/src/main.rs
Closes #32.
Please let me know if I am doing something that is naive. 
I also took the leeway to add a CHANGELOG.md. Please let me know if you suggest I not add that.
=> summarize (feature): adds percent-above cli argument 

crox/Cargo.toml, crox/src/main.rs, measureme/Cargo.toml
The version number bump is due to the breaking change in #41.
=> 0.3.0 release

measureme/Cargo.toml, measureme/src/lib.rs
This is part of an experiment to port rustc to wasi. (cc https://github.com/rust-lang/miri/issues/722)
Webassembly doesn't support any mmap like mechanism.
=> Support wasm and wasi

CHANGELOG.md, mmview/src/main.rs, summarize/src/analysis.rs
I also made it easier to troubleshoot invalid event files which can cause assertion failures in `summarize`.
=> [mmview] Add a thread-id filter argument

CHANGELOG.md, crox/src/main.rs, summarize/Readme.md, summarize/src/analysis.rs, summarize/src/diff.rs, summarize/src/main.rs, summarize/src/query_data.rs, summarize/src/signed_duration.rs
=> [summarize] Implement `diff` support for comparing profiles

crox/src/main.rs
collapses the threads by finding the thread that ended first and then map the threads to that if the active time for the threads is is not overlapping
=> add command to collaps threads with no overlapping events

crox/src/main.rs
to reduce the size of the generated json file
fixes #47
=> use complete events in crox

crox/src/main.rs
some files is to large to show in the browser
filter_duration_ms filter out all events that is shorter than specified limit
=> add option to crox to filter out short events

measureme/src/profiling_data.rs
helped with finding https://github.com/rust-lang/rust/pull/65137
=> make it clear what events that was involved in the panic

CHANGELOG.md, measureme/Cargo.toml, measureme/src/lib.rs, measureme/src/profiler.rs
This PR adds a RAII-based API for recording events in preparation for replacing `(start, end)` event pairs with single "interval" events. It also bumps the version to 0.4.0 so the new API can be used in `rustc`. 
=> Add RAII-based API for recording events and bump version to 0.4.0

measureme/src/file_header.rs, measureme/src/lib.rs, measureme/src/profiler.rs, measureme/src/profiling_data.rs, measureme/src/serialization.rs, measureme/src/stringtable.rs, summarize/src/analysis.rs, summarize/src/query_data.rs
This is useful because data generated from an actual `Profiler` contains unpredictable timestamps.
=> measureme: Add a ProfilingDataBuilder that can be used for constructing test data.

flamegraph/src/main.rs, stack_collapse/src/main.rs, tools_lib/src/stack_collapse.rs
part of the problem seen in https://github.com/rust-lang/rust/issues/65788
most of the remaining unaccounted for time I think is the main threads wait for the link to start after codegen_crate is done.
have compared the times from crox with the per thread data in the flamegraph and they match with this PR
=> stack collaps events from multiple threads correct

summarize/Readme.md
Follow-up for rust-lang/rustc-guide#491
=> Fix broken link on README

CHANGELOG.md, crox/src/main.rs, flamegraph/src/main.rs, measureme/src/event.rs, measureme/src/file_header.rs, measureme/src/lib.rs, measureme/src/profiler.rs, measureme/src/profiling_data.rs, measureme/src/raw_event.rs, measureme/src/serialization.rs, measureme/src/testing_common.rs, stack_collapse/src/main.rs, summarize/src/analysis.rs, tools_lib/src/stack_collapse.rs
This reduces the number of events that need to be recorded.
~~Currently the PR updates all tools except `stack_collapse` which seems to be in flux at the moment. It also does not yet use the raw event format (i.e. the number of bits used for timestamps and thread-ids is unnecessarily high).~~
I intend to optimize the raw format of events and the string table in subsequent PR. This one already contains enough changes.
@wesleywiser Let me know if prefer the PR to be split up into more commits.
=> Replace (start, stop) event pairs with interval events.

crox/Cargo.toml, crox/src/main.rs, summarize/Cargo.toml, summarize/src/analysis.rs, summarize/src/diff.rs, tools_lib/Cargo.toml, tools_lib/src/stack_collapse.rs
Tries to fix Issue #77 .
1. Replaces HashMap with `rustc_hash::FxHashMap`.
2. Replaces HashSet with `rustc_hash::FxHashSet`.
Based on @michaelwoerister 's help,  I fixed to replace `HashMap::with_capacity` with `FxHashMap::with_capacity_and_hasher`. Thanks.
=> Replace HashMap with `rustc_hash::FxHashMap` in Tools

.travis.yml, measureme/src/serialization.rs
Using the crate as part of `rustc` requires that it build on nightly. Let's make sure we catch cases early where it doesn't. This PR contains a fix for such a problem.
=> Make sure all crates compile on nightly and beta.

CHANGELOG.md, analyzeme/Cargo.toml, analyzeme/src/profiling_data.rs, crox/src/main.rs, measureme/src/stringtable.rs
add parameter `--dir` that merges all events in the directory to one chrome_profiler.json file.
makes it possible to give multiple file_prefixes and will merge all of them to one chrome_profiler.json file.
also use the crate name from the cmd metadata to show what process_id  is from what crate build.
=> use meta data in crox events to be able to merge multiple logs

analyzeme/src/event.rs, analyzeme/src/profiling_data.rs, analyzeme/src/testing_common.rs, crox/src/main.rs, measureme/src/file_header.rs, measureme/src/lib.rs, measureme/src/profiler.rs, measureme/src/raw_event.rs, measureme/src/stringtable.rs, mmview/src/main.rs
This restricts us to timestamps of at most ~78 hours after process start which seems acceptable. 
The PR reduces the size of `RawEvent` (and thus the size of our event stream files) by 25%.
=> Only use 48 bits for encoding timestamps and 32 bits for encoding thread IDs in RawEvent in order to make it smaller.

analyzeme/benches/serialization_bench.rs, analyzeme/src/testing_common.rs, analyzeme/tests/serialization.rs, measureme/Cargo.toml, measureme/src/file_serialization_sink.rs, measureme/src/serialization.rs
This PR makes the `FileSerializationSink` exactly as fast as the `MmapSerializationSink` in the benchmarks we have. But I only tested on Linux and I also remember that the benchmarks were no good indication of performance when used in `rustc`.
It would be nice if we could get rid of the `MmapSerializationSink` because it keeps everything in memory until the end.
I wonder how much work it would be to have benchmarks that actually run `rustc`. It's a hassle to test this manually.
=> Optimize FileSerializationSink by using parking_lot::Mutex and avoiding heap allocations in write_atomic.

analyzeme/Cargo.toml, analyzeme/src/lib.rs, analyzeme/src/profiling_data.rs, analyzeme/src/stringtable.rs, measureme/src/file_header.rs, measureme/src/lib.rs, measureme/src/stringtable.rs
This PR makes the encoding for the string table more compact, as described in [measureme::stringtable's module-level documentation](https://github.com/michaelwoerister/measureme/blob/utf8-based-stringtable-encoding/measureme/src/stringtable.rs#L1-L38). It also moves the code for reading string tables into the `analyzeme` crate. 
This PR concludes my planned changes to the file format for the time being. We'll need some more changes to the API in order to facilitate recording query keys but those should not require updating perf.rlo. 
It's probably best to review the first commit in isolation.
=> Use more compact encoding for the string table

summarize/src/analysis.rs, summarize/src/query_data.rs
Fixes the issue found in https://github.com/rust-lang/rust/pull/66981. The should be correct but this could be cleaned up even more if the questions in https://github.com/rust-lang/measureme/issues/75 were properly answered. Would be good to do that before the next bigger release.
r? @wesleywiser or @andjo403
=> Support query events stacked on incremental_load events in summarize.

measureme/src/file_serialization_sink.rs, measureme/src/serialization.rs
This method is optimized for cases where the bytes to be written are already available in serialized form. This is a case that will occur quite a bit once we record query keys.
=> SerializationSink: Add write_bytes_atomic method. 

analyzeme/src/stringtable.rs, analyzeme/src/testing_common.rs, measureme/src/file_header.rs, measureme/src/profiler.rs, measureme/src/raw_event.rs, measureme/src/stringtable.rs
This PR removes some unnecessary overhead from the StringTable format. 
> With this commit only "virtual" StringIds get an entry in the index table and regular StringIds
store an actual address instead of index table key. That makes the index data a lot smaller
and removes the need to do a table lookup for regular StringIds.
This optimization becomes important when recording query keys because we allocate a lot more string data in that case.
~~This PR also contains the changes from https://github.com/rust-lang/measureme/pull/97. Feel free to review/merge all at once or separately.~~
=> Virtual instead of reserved string ids

CHANGELOG.md, analyzeme/Cargo.toml, crox/Cargo.toml, flamegraph/Cargo.toml, measureme/Cargo.toml, measureme/src/profiler.rs, mmview/Cargo.toml, stack_collapse/Cargo.toml, summarize/Cargo.toml
This PR adds a small piece of functionality that is needed for query key recording. In `rustc` we (will) use the `DepNodeIndex` as the virtual `StringId` that ends up being the `event_id`. However, the `DepNodeIndex` is often only generated after we already started recording the corresponding event. So we need a way of overwriting the `event_id` once we know what to actually set it to.
This PR also bumps the version to `0.6.0` for _all_ crates in the repo. As @Mark-Simulacrum pointed out, it makes sense to have one version number for the entire workspace (with the expectation that the tools and libraries of the same version number are always compatible with each other).
=> Add API for overriding initial event_id before recording an event and bump version to 0.6.0

analyzeme/src/event.rs, analyzeme/src/profiling_data.rs, analyzeme/src/stringtable.rs, analyzeme/src/testing_common.rs, measureme/src/event_id.rs, measureme/src/file_header.rs, measureme/src/lib.rs, measureme/src/profiler.rs, measureme/src/raw_event.rs
This is implemented by encoding arguments as part of the `event_id` using the following grammar:
```
<event_id> = <label> {<argument>}
<label> = <text>
<argument> = '\x1E' <text>
<text> = regex([^[[:cntrl:]]]+) // Anything but ASCII control characters
```
This can be extended in the future to also encode the "category" that specify in `rustc` but don't use anywhere. The grammar uses ASCII control characters as separators. I'm not sure how much I like the grammar. It's something that works for now but I don't consider it great.
I'm debating whether `event_id` should get a new type `struct EventId(StringId)`. That way we could ensure at compile time that only syntactically correct strings are used as `event_id`s...
=> Add support of having arguments on events.

.travis.yml, analyzeme/Cargo.toml, crox/Cargo.toml, flamegraph/Cargo.toml, measureme/Cargo.toml, measureme/src/event_id.rs, measureme/src/raw_event.rs, mmview/Cargo.toml, stack_collapse/Cargo.toml, summarize/Cargo.toml
This PR
- fixes a compilation error on big endian platforms
- adds a big endian `cargo check` build to CI, so we catch compilation errors like these early next time
- bumps the version to `0.7.1` so we can use that to unblock https://github.com/rust-lang/rust/pull/67397.
~~This PR should fail until the big endian specific error uncovered [here](https://github.com/rust-lang/rust/pull/67397#issuecomment-568295509) is fixed.~~
=> Fix big-endian build and add CI tests for it.

summarize/src/analysis.rs
Adjusts the logic in `summarize` according to https://github.com/rust-lang/measureme/issues/75#issuecomment-563137947. 
The differences in absolute numbers should be small. But it is more consistent, I think.
Fixes https://github.com/rust-lang/measureme/issues/75.
=> summarize: Make incr-cache-loading and query-blocking contribute to self-time of query.

crox/src/main.rs
hade been nice to have some reserved names (eg. def_id, cgu_id ...) for the additional data now I have only enumerated them.
eg. of how it looks in chrome://tracing/
=> add additinonal data to crox events

summarize/Readme.md
The rustc-guide is being renamed to the rustc-dev-guide. The discussion is in rust-lang/rustc-guide#470.
This PR revises rustc-guide to rustc-dev-guide in the Readme Markdown file.
Transition tracker: rust-lang/rustc-guide#602
=> Update rustc-guide to rustc-dev-guide

summarize/src/analysis.rs, summarize/src/main.rs
The [boa project](https://github.com/boa-dev/boa) is using measureme to trace their own performance. This lets them use the `summarize` tool which was previously only useful to rustc because it cared about very specific event kinds.
=> Make summarize useful to data producers other than rustc

.travis.yml, measureme/src/lib.rs
The documentation had a number of out-dated references and broken links.
The links are replaced with intra-doc links and a lint is denied to
ensure they remain valid.
(Note, however that the intra-doc links only work with a nightly rustdoc AFAIK…)
=> Adjust top-level documentation for current state

Cargo.toml, analyzeme/src/stringtable.rs, measureme/src/file_serialization_sink.rs, measureme/src/mmap_serialization_sink.rs, measureme/src/profiler.rs, measureme/src/serialization.rs, mmview/src/main.rs
See individual commits for descriptions.
If I come across other problems I might add onto what is currently here.
=> Assorted fixes and improvements

analyzeme/src/profiling_data.rs
perf.rust-lang.org is using this to avoid writing out profiles to disk when loading them over the network.
=> In-memory construction of profiling data

summarize/Readme.md
See https://github.com/rust-lang/rust/pull/73964.
The choices are either to link to `stage1` with rustup or build stage 2; this recommends to build stage2 to be consistent with the existing docs.
=> Update README for changes in x.py defaults

analyzeme/src/stringtable.rs, measureme/src/file_header.rs, measureme/src/profiler.rs, measureme/src/raw_event.rs, measureme/src/stringtable.rs
In the interest of simplifying dependency management for measureme and ultimately rustc, this refactors measureme to remove its dependency on the byteorder crate.
=> Remove byteorder dependency

measureme/Cargo.toml
I just realized we forgot to do this in #125
=> Remove byteorder dependency from measureme/Cargo.toml

analyzeme/src/stringtable.rs, measureme/src/file_header.rs, measureme/src/stringtable.rs
This PR changes the encoding for string references within the `StringTable` to use 5 bytes instead of 4 bytes. This way we can address 4 GB of data instead of 1 GB. The code becomes quite a bit simpler because we can remove a lot of manual bit-fiddling operations.
The only downside of the new approach is that string reference heavy data (e.g. from recording query keys) becomes about 5% larger. Between the larger address space support and the maintainability improvements this seems like an acceptable tradeoff to me. (I also have a half-done implementation of the same functionality without the additional space requirements -- but that turned out to make for such messy de-/serialization code that I abandoned it)
The size of profiling data that is collected without query keys should not be …
=> Allow StringTable to use the full 32-bit address space

analyzeme/src/profiling_data.rs
Do we expect to keep the compatibility for deserializing 0.7 (i.e., older) profile data for some time with newer analyzeme as well? That would be great from perf.rlo's side but we can depend on an older version too if needed.
=> Decode paged buffers from memory

measureme/Cargo.toml, measureme/src/counters.rs, measureme/src/lib.rs, measureme/src/profiler.rs, measureme/src/raw_event.rs
*Note: this is a companion to https://github.com/rust-lang/rust/pull/78781, and duplicates some information with it for convenience*
I'd like to start by thanking @alyssais, @cuviper, @edef1c, @glandium, @jix, @Mark-Simulacrum, @m-ou-se, @mystor, @nagisa, @puckipedia, and @yorickvP, for all of their help with testing, and valuable insight and suggestions.
Getting here wouldn't have been possible without you!
(If I've forgotten anyone please let me know, I'm going off memory here, plus some discussion logs)
This PR adds support for counting hardware events such as "instructions retired" (as opposed to being limited to time measurements), using the `rdpmc` instruction on `x86_64` Linux.
Additionally, as `asm!` is used, `measureme` needs to built with nightly Rust, and with `features = …
=> Hardware performance counter support (via `rdpmc`).

analyzeme/src/lib.rs, measureme/src/lib.rs
- Remove unnecessary explicit links
- Remove `deny(intra_doc_resolution_failure)`: it's both renamed and on by default, so it will be caught by `deny(warnings)`.
=> Cleanup intra-doc links

summarize/src/analysis.rs
as the time for blocked events is increased think that also the invocation count shall be increased.
was confused when looking at the result from https://github.com/rust-lang/rust/pull/79706 where parallell compiler is tested,
some queries was taking long time when running in parallell so was looking in the query after the problem as the invocation count was 1, but in many cases the problem was that the same query was executed in multiple threads at the same time resulting in blocked query events.
=> add to invocation count for blocked events

measureme/src/counters.rs
I meant to get these done before landing #143, but that happened too soon. Will keep this as draft until ready.
The inline `asm!` changes I've validated by comparing the old and new versions (they produce identical assembly in godbolt set to "Intel dialect", i.e. the AT&T dialect gets parsed and rewritten to the Intel dialect I originally used).
=> Minor tweaks to the measureme::counters module.

measureme/src/file_header.rs
=> return error if the file is too small instead of panicking

summarize/src/aggregate.rs, summarize/src/main.rs
For my ongoing `rdpmc` instruction-counting work I've ended up with *a lot* of profile results (over 700 and there were hundreds I've already removed), that I don't really have any tools to analyze in-depth.
The fundamental problem is that e.g. `summarize summarize` will effectively sum together many small intervals between consecutive timestamps/instruction counts, so the distribution of variance in individual samples (of the clock/instruction counter), or the exact sources of large variances, are lost in the summary.
This PR seeks to address that by introducing a `summarize aggregate` command specifically for sets of deterministic runs (identical in all respects *except* the timestamps themselves). Example output:
```
$ summarize aggregate …
```
=> summarize: add "aggregate" sub-command for analyzing sets of profiles.

crox/src/main.rs
Hopefully closes #154 
Untested, but I think should be fine. Previously, `crox --dir <dir>` was looking for `.events` files, while `ProfileData` (and AFAICS everything else) works with `mm_profiledata`. This PR updates the file extension filter so that `crox --dir` may generate results without having to rename the world.
=> Crox: Collect mm_profiledata files in directory

measureme/Cargo.toml, measureme/src/counters.rs
memmap is no longer maintained. memmap2 is a fork that is still maintained. https://rustsec.org/advisories/RUSTSEC-2020-0077.html
cc  https://github.com/rust-lang/rust/pull/83236
Fixes #153
=> Update memmap to memmap2.

measureme/src/rustc.rs, summarize/src/analysis.rs, summarize/src/main.rs, summarize/src/query_data.rs
Relies on changes in https://github.com/rust-lang/rust/pull/86619 where you can read a bit more about the goals of this change.
Putting into draft mode until https://github.com/rust-lang/rust/pull/86619 is more fully discussed.
=> Handle new self-profiling information for incr-comp hash fingerprints

summarize/src/aggregate.rs
This incorrect code was snuck in in #169. The code as it stands now should be exactly equivalent to how `summarize aggregate`  
worked before #169 landed. We are filtering out the newly "integer" type events and so the code can assume (as it did before) that it's only dealing with time related events.
r? @michaelwoerister
=> Fix wrong unreachable code in summarize aggregate

measureme/src/rustc.rs, summarize/src/analysis.rs
This makes it so that in summarize we only add to the artifact size if that event label is "ArtifactSize"
=> Check the artifact size event kind in summarize

summarize/src/analysis.rs, summarize/src/query_data.rs
Artifact size events can have the same label. When summarizing we should dedup these events by their label.
=> Dedup artifact sizes by label when summarizing

crox/Readme.md, flamegraph/README.md, stack_collapse/README.md, summarize/Readme.md
The master branch sometimes contains breaking changes that will not work when run against artifacts created by the latest nightly compiler. We should encourage users to install the latest version that we know works with nightly rustc. Right now that is version 9.1.2
=> Install instructions should point to using latest version which works

CHANGELOG.md, analyzeme/Cargo.toml, analyzeme/src/lib.rs, analyzeme/src/profiling_data.rs, crox/Cargo.toml, flamegraph/Cargo.toml, measureme/Cargo.toml, measureme/src/lib.rs, measureme/src/profiler.rs, measureme/src/stringtable.rs, mmview/Cargo.toml, stack_collapse/Cargo.toml, summarize/Cargo.toml, version_checker/Cargo.toml
Makes a couple of methods in `ProfilingData` public in order to make it easier to start supporting older file formats in v10.0.0.
r? @rylev & @wesleywiser
=> Prepare 9.2.0 release

.github/workflows/rust.yml
This is based on how [miri handles bors](https://github.com/rust-lang/miri/blob/6cf851f6d43bff1e8ac1421cbf3c6a8d20f89560/.github/workflows/ci.yml#L119-L140).
=> Add jobs to make bors able to detect success or failure

measureme/src/counters.rs
when I tried to rebase https://github.com/rust-lang/rust/pull/78781 I noticed that due to https://github.com/rust-lang/rust/pull/84658 this code did not compile any longer.
also due to https://github.com/rust-lang/rust/pull/83387 is merged we can use the intel asm and remove the duplication of all asm instructions
=> Avoid using ebx as an asm! operand

measureme/src/counters.rs
Rust minimum LLVM version still do not support Intel syntax inline asm
missed one in the last PR
r? @eddyb
=> counters: use AT&T inline asm syntax for older LLVM.

README.md, crox/Cargo.toml, crox/README.md, flamegraph/README.md, stack_collapse/README.md, summarize/README.md
We now have a [stable](https://github.com/rust-lang/measureme/tree/stable) branch which points to the v10.0.0. We can now encourage folks to install off this branch instead of from a specific version or from master. 
(I also updated the READMEs with a few small fixes) 
r? @michaelwoerister 
Fixes #182
=> Change install instructions to use stable branch

measureme/src/counters.rs, measureme/src/lib.rs
nightly rust was previously required because of the usage of the
unstable `asm` feature which was stabilized in version 1.59.0
=> Allow to build measureme on stable rust

crox/Cargo.toml, crox/src/main.rs, flamegraph/Cargo.toml, flamegraph/src/main.rs, mmedit/Cargo.toml, mmedit/src/main.rs, mmview/Cargo.toml, mmview/src/main.rs, stack_collapse/Cargo.toml, stack_collapse/src/main.rs, summarize/Cargo.toml, summarize/src/main.rs
As structopt is now in maintenance mode change to Clap.
=> Change Cli parser from StructOpt to Clap

crox/src/main.rs
```
error: unexpected end of input, unexpected token in nested attribute, expected ident
--> crox/src/main.rs:35:13
|
35 |     #[serde()]
|     
```
=> Remove malformed `serde` attribute

decodeme/src/event.rs, measureme/src/event_id.rs
As it only seems that control chars is not allowed in the EventId texts is to allow for future tags I think excluding the whitespace control chars is ok.
What I can see right now the only tag used is for arguments and is '\x1E'.
fixes #207
cc @michaelwoerister
=> Allow whitespace control chars in EventId texts.

measureme/Cargo.toml
Sync with https://github.com/rust-lang/rust/pull/114418
=> bump parking_lot to 0.12 to sync with rustc

.github/workflows/nightly.yml
This PR adds a CI workflow that checks each day whether we can handle the output of the nightly compiler's self-profile data with `measureme` from the `stable` branch.
=> Add a CI workflow to check the stable branch with nightly compiler output

analyzeme/src/testing_common.rs, measureme/src/stringtable.rs
The change here makes `StringId::new` and `StringId::new_virtual` backwards compatible with 10.x, so that we don't require unnecessary churn when updating to 11.0.0.
=> Prepare 11.0.0 release

.github/workflows/nightly.yml, .github/workflows/rust.yml, CHANGELOG.md, flamegraph/Cargo.toml, measureme/src/raw_event.rs
This PR fixes the big endian regression tests. Apparently, the have not actually run `cargo check` with a big endian target for a while. The PR also switches the GH action jobs to use a matrix and replaces the unmaintained action-rs with something more current. It also fixes the big-endian-only compilation error that the now fixed tests are running into.
This should unblock https://github.com/rust-lang/rust/pull/119111, once we've done a 11.0.1 release.
=> Fix compilation error and regression tests for big endian platforms

.github/workflows/rust.yml
Bors is overkill for this repo anyway.
=> Remove bors CI config

.github/workflows/nightly.yml, .github/workflows/publish.yml, .github/workflows/rust.yml, CHANGELOG.md, analyzeme/Cargo.toml, crox/Cargo.toml, decodeme/Cargo.toml, flamegraph/Cargo.toml, measureme/Cargo.toml, measureme/src/raw_event.rs, mmedit/Cargo.toml, mmview/Cargo.toml, stack_collapse/Cargo.toml, summarize/Cargo.toml, version_checker/Cargo.toml
See https://github.com/rust-lang/measureme/releases/tag/11.0.1
=> Update stable branch to 11.0.1 release

analyzeme/src/testing_common.rs, crox/Cargo.toml, crox/src/main.rs, flamegraph/Cargo.toml, flamegraph/src/main.rs, mmedit/Cargo.toml, mmedit/src/main.rs, mmview/Cargo.toml, mmview/src/main.rs, stack_collapse/Cargo.toml, stack_collapse/src/main.rs, summarize/Cargo.toml, summarize/src/main.rs
Looks working. UI layout changed, but i guess this acceptable.
=> bump clap 3 -> 4

.github/workflows/publish.yml, CHANGELOG.md, analyzeme/Cargo.toml, crox/Cargo.toml, decodeme/Cargo.toml, decodeme/LICENSE-APACHE, decodeme/LICENSE-MIT, flamegraph/Cargo.toml, measureme/Cargo.toml, measureme/LICENSE-APACHE, measureme/LICENSE-MIT, mmedit/Cargo.toml, mmview/Cargo.toml, stack_collapse/Cargo.toml, summarize/Cargo.toml, version_checker/Cargo.toml
This is a part of <https://github.com/rust-lang/measureme/issues/229>.
There should be no code change between 10.1.3,
The only change is including open source licenses in Cargo.toml
and the distributable tarball (`.crate` file generated by `cargo package/publish`).
(I'll update changelog after this PR is submitted)
=> chore: prepare 10.1.3 release for decodeme/mesureme

.github/workflows/publish.yml
This is a preparation of v12 release.
See #229 and #233
=> chore: publish also decodeme and analyzeme in CI

CHANGELOG.md, Cargo.toml
Block on <https://github.com/rust-lang/measureme/pull/232> and <https://github.com/rust-lang/measureme/pull/234>.
Will update changelog after this PR is created.
=> chore: prepare for v12 release

Cargo.toml, measureme/Cargo.toml, measureme/src/counters.rs
I was trying to build ohos rustc targets. but blocked. It seems that` perf-event-open-sys` support is not good(https://github.com/rust-lang/measureme/issues/237#issuecomment-2484574815).
The new `perf-event-open-sys2` supports this which is an actively maintained fork.
cc https://github.com/rust-lang/measureme/issues/237
=> Cofigurate out `ohos` target's dependecies  to avoid compilation crashes

decodeme/src/lib.rs
Earlier today we had an interesting [perf run](https://github.com/rust-lang/rust/pull/133502#issuecomment-2505625977): a try build seemingly created an invalid .mm_profdata file. This caused a panic in the event decoder checks (that, in turn, made the perf collector panic and infinite loop on the same benchmark 😅), although it supports errors in the file header and magic values. 
This PR expands the error checking and turns these panics into errors so that they can be handled upstream, even though the file the decoder was asked to read is completely invalid. AFAICT it was only the header that was present -- though I can find out more about it if you want?.
=> don't panic on missing page tags

CHANGELOG.md, Cargo.toml
I've been trying to promote openharmony targets to tier2 with host tools.
and there was a modfify made on the measureme tool. https://github.com/rust-lang/measureme/pull/238 (merged)
I'd like to apply this modification through a new version. 
it's convenient for you to review it?. Really appreciate it.  @michaelwoerister @wesleywiser @weihanglo
=> Bump measureme version to 12.0.1

analyzeme/src/analysis.rs, measureme/src/rustc.rs
This adds support to the analysis module for aggregated query cache hit counts, which were added to rustc in https://github.com/rust-lang/rust/pull/142978. I tried to keep compatibility with the original (very expensive) per-query-invocation cache hit counters.
=> Add support for reading aggregated query cache hit counts

.github/workflows/rust.yml
Before this PR is merged, merge queue should be configured for the "success" job (for the `master` branch), and the option "require branches to be up-to-date" should be unchecked.
=> Use merge queues for the repository
