rust-lang/measureme

README.md, measureme/Cargo.toml
=> Add CI badges

measureme/src/event.rs, measureme/src/profiling_data.rs, measureme/src/testing_common.rs
=> Add thread id to Event

Cargo.toml, mmview/Cargo.toml, mmview/src/main.rs
I found this helpful while working on using `measureme` in `rustc`.
=> Add a basic tool for printing the event data

measureme/Cargo.toml
=> Update measureme Cargo.toml & version so we can publish

.travis.yml
Fixes #22 
r? @michaelwoerister
=> Update Travis configuration to use stable

measureme/src/mmap_serialization_sink.rs
=> MmapSerializationSink: Don't panic in Drop::drop().

measureme/Cargo.toml
=> Bump version after MmapSerializationSink bug fix.

Cargo.toml, measureme/src/lib.rs, stack_collapse/Cargo.toml, stack_collapse/README.md, stack_collapse/src/main.rs, stack_collapse/src/stack_collapse.rs
=> Add a stack-collapse tool for generating flamegraphs

summarize/Readme.md
=> Write documentation for the summarize tool

README.md
=> fix: Fix broken link

measureme/src/profiler.rs, measureme/src/stringtable.rs
=> Store some metadata about the profile in a reserved string table slot

crox/src/main.rs
found that I hade made an assumption that the thread_id stated the order of the start times per thread but that is not the case threads can be started long before the first event
=> correct fault in collapse-threads command

crox/src/main.rs
made minimum_duration an required argument by mistake
=> make minimum_duration optional in crox

measureme/src/lib.rs, measureme/src/profiler.rs, measureme/src/stringtable.rs, measureme/src/testing_common.rs
=> Fix some warnings that prevent measureme being built as a path dependency of the compiler.

CHANGELOG.md, summarize/src/diff.rs, summarize/src/main.rs, summarize/src/query_data.rs
self_time_change is percentage change of self_time from base.
change to if base have value but the change do not
the base values is inverted and if the change have value
but the base do not the changes values is used.
fixes https://github.com/rust-lang/measureme/issues/81
=> add self_time_change to summarize diff

analyzeme/src/event.rs, analyzeme/src/lib.rs, analyzeme/src/lightweight_event.rs, analyzeme/src/profiling_data.rs, analyzeme/src/stack_collapse.rs, analyzeme/src/testing_common.rs, analyzeme/src/timestamp.rs, crox/src/main.rs, measureme/src/stringtable.rs, summarize/src/analysis.rs
Tries to fix #80 according to @michaelwoerister 's comments.
=> Add LightweightEvent for making `Event` string fields in lazy

CHANGELOG.md, measureme/Cargo.toml, measureme/src/lib.rs
r? @wesleywiser 
cc @jackpot51
=> Bump version to 0.5

analyzeme/Cargo.toml, analyzeme/benches/serialization_bench.rs, analyzeme/src/lightweight_event.rs, analyzeme/src/profiling_data.rs, analyzeme/src/stack_collapse.rs, analyzeme/src/stringtable.rs, analyzeme/src/testing_common.rs, analyzeme/tests/serialization.rs, crox/Cargo.toml, flamegraph/Cargo.toml, measureme/Cargo.toml, mmview/Cargo.toml, mmview/src/main.rs, stack_collapse/Cargo.toml, summarize/Cargo.toml, summarize/src/analysis.rs
This PR makes the output of `mmview` a bit more readable, runs `cargo fmt`, and bumps the version to 0.7.0. 
=> Bump to 0.7.0

crox/Cargo.toml, flamegraph/Cargo.toml, mmview/Cargo.toml, stack_collapse/Cargo.toml, summarize/Cargo.toml
This removes duplicate crates from the build
=> Upgrade to structopt 0.3

stack_collapse/README.md
=> stack-collapse -> stack_collapse in README

measureme/Cargo.toml, measureme/src/event_id.rs
=> Add a way to create an `EventId` with multiple arguments

measureme/src/stringtable.rs
=> Avoid lint on nightly

CHANGELOG.md, analyzeme/Cargo.toml, crox/Cargo.toml, decodeme/Cargo.toml, flamegraph/Cargo.toml, measureme/Cargo.toml, mmedit/Cargo.toml, mmview/Cargo.toml, stack_collapse/Cargo.toml, summarize/Cargo.toml, version_checker/Cargo.toml
This prepares all crates for a v10.0.0 release.
=> Prepare v10.0.0 release

summarize/Cargo.toml
=> Update `prettytable` to 0.10

.github/workflows/publish.yml, CHANGELOG.md
Updated the change log and applied the nit fix mentioned here:
https://github.com/rust-lang/measureme/pull/221/files#r1448528749
=> Prepare release 11.0.1

analyzeme/Cargo.toml, crox/Cargo.toml, decodeme/Cargo.toml, flamegraph/Cargo.toml, measureme/Cargo.toml, mmedit/Cargo.toml, mmview/Cargo.toml, stack_collapse/Cargo.toml, summarize/Cargo.toml, version_checker/Cargo.toml
=> Update crate versions to 11.0.1

CHANGELOG.md, Cargo.toml
Related to https://github.com/rust-lang/measureme/pull/247.
=> Bump version to 12.0.2

CHANGELOG.md, Cargo.toml
Here we go again.. hopefuly this time we'll be able to test the full publish pipeline.
=> Bump version to 12.0.3
